/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Android-Action-Bar-Icon-Pack\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-rating-bad' : '&#xe020;',
			'icon-action-settings' : '&#xe013;',
			'icon-action-search' : '&#xe012;',
			'icon-action-help' : '&#xe011;',
			'icon-action-about' : '&#xe010;',
			'icon-navigation-refresh' : '&#xe009;',
			'icon-navigation-previous-item' : '&#xe008;',
			'icon-navigation-next-item' : '&#xe007;',
			'icon-navigation-forward' : '&#xe006;',
			'icon-navigation-expand' : '&#xe005;',
			'icon-navigation-collapse' : '&#xe004;',
			'icon-navigation-cancel' : '&#xe003;',
			'icon-navigation-back' : '&#xe001;',
			'icon-navigation-accept' : '&#xe002;',
			'icon-av-pause-over-video' : '&#xe097;',
			'icon-av-pause' : '&#xe096;',
			'icon-av-next' : '&#xe095;',
			'icon-av-make-available-offline' : '&#xe094;',
			'icon-av-full-screen' : '&#xe093;',
			'icon-av-fast-forward' : '&#xe092;',
			'icon-av-download' : '&#xe091;',
			'icon-av-add-to-queue' : '&#xe090;',
			'icon-images-slideshow' : '&#xe083;',
			'icon-images-rotate-right' : '&#xe082;',
			'icon-images-rotate-left' : '&#xe081;',
			'icon-images-crop' : '&#xe080;',
			'icon-location-web-site' : '&#xe073;',
			'icon-location-place' : '&#xe072;',
			'icon-location-map' : '&#xe071;',
			'icon-location-directions' : '&#xe070;',
			'icon-social-share' : '&#xe06a;',
			'icon-social-send-now' : '&#xe069;',
			'icon-social-reply-all' : '&#xe068;',
			'icon-social-reply' : '&#xe067;',
			'icon-social-person' : '&#xe066;',
			'icon-social-group' : '&#xe065;',
			'icon-social-forward' : '&#xe064;',
			'icon-social-chat' : '&#xe063;',
			'icon-social-cc-bcc' : '&#xe062;',
			'icon-social-add-person' : '&#xe061;',
			'icon-social-add-group' : '&#xe060;',
			'icon-content-unread' : '&#xe057;',
			'icon-content-undo' : '&#xe056;',
			'icon-content-split' : '&#xe055;',
			'icon-content-select-all' : '&#xe054;',
			'icon-content-save' : '&#xe053;',
			'icon-content-remove' : '&#xe052;',
			'icon-content-read' : '&#xe051;',
			'icon-content-picture' : '&#xe050;',
			'icon-content-paste' : '&#xe04f;',
			'icon-content-new-picture' : '&#xe04e;',
			'icon-content-new-event' : '&#xe04d;',
			'icon-content-new-email' : '&#xe04c;',
			'icon-content-new-attachment' : '&#xe04b;',
			'icon-content-new' : '&#xe04a;',
			'icon-content-merge' : '&#xe049;',
			'icon-content-import-export' : '&#xe048;',
			'icon-content-event' : '&#xe047;',
			'icon-content-email' : '&#xe046;',
			'icon-content-edit' : '&#xe045;',
			'icon-content-discard' : '&#xe044;',
			'icon-content-cut' : '&#xe043;',
			'icon-content-copy' : '&#xe042;',
			'icon-content-backspace' : '&#xe041;',
			'icon-content-attachment' : '&#xe040;',
			'icon-collections-view-as-list' : '&#xe037;',
			'icon-collections-view-as-grid' : '&#xe036;',
			'icon-collections-sort-by-size' : '&#xe035;',
			'icon-collections-new-label' : '&#xe034;',
			'icon-collections-labels' : '&#xe033;',
			'icon-collections-go-to-today' : '&#xe032;',
			'icon-collections-collection' : '&#xe031;',
			'icon-collections-cloud' : '&#xe030;',
			'icon-rating-not-important' : '&#xe025;',
			'icon-rating-important' : '&#xe024;',
			'icon-rating-half-important' : '&#xe023;',
			'icon-rating-good' : '&#xe022;',
			'icon-rating-favorite' : '&#xe021;',
			'icon-hardware-phone' : '&#xe00e;',
			'icon-hardware-mouse' : '&#xe0f6;',
			'icon-hardware-keyboard' : '&#xe0f5;',
			'icon-hardware-headset' : '&#xe0f4;',
			'icon-hardware-headphones' : '&#xe0f3;',
			'icon-hardware-gamepad' : '&#xe0f2;',
			'icon-hardware-dock' : '&#xe0f1;',
			'icon-hardware-computer' : '&#xe0f0;',
			'icon-alerts-and-states-warning' : '&#xe0e3;',
			'icon-alerts-and-states-error' : '&#xe0e2;',
			'icon-alerts-and-states-airplane-mode-on' : '&#xe0e1;',
			'icon-alerts-and-states-airplane-mode-off' : '&#xe0e0;',
			'icon-device-access-volume-on' : '&#xe0d9;',
			'icon-device-access-volume-muted' : '&#xe0d8;',
			'icon-device-access-video' : '&#xe0d7;',
			'icon-device-access-usb' : '&#xe0d6;',
			'icon-device-access-time' : '&#xe0d5;',
			'icon-device-access-switch-video' : '&#xe0d4;',
			'icon-device-access-switch-camera' : '&#xe0d3;',
			'icon-device-access-storage' : '&#xe0d2;',
			'icon-device-access-secure' : '&#xe0d1;',
			'icon-device-access-sd-storage' : '&#xe0d0;',
			'icon-device-access-screen-rotation' : '&#xe0cf;',
			'icon-device-access-screen-locked-to-portrait' : '&#xe0ce;',
			'icon-device-access-screen-locked-to-landscape' : '&#xe0cd;',
			'icon-device-access-ring-volume' : '&#xe0cc;',
			'icon-device-access-not-secure' : '&#xe0cb;',
			'icon-device-access-new-account' : '&#xe0ca;',
			'icon-device-access-network-wifi' : '&#xe0c9;',
			'icon-device-access-network-cell' : '&#xe0c8;',
			'icon-device-access-mic-muted' : '&#xe0c7;',
			'icon-device-access-mic' : '&#xe0c6;',
			'icon-device-access-location-searching' : '&#xe0c5;',
			'icon-device-access-location-off' : '&#xe0c4;',
			'icon-device-access-location-found' : '&#xe0c3;',
			'icon-device-access-flash-on' : '&#xe0c2;',
			'icon-device-access-flash-off' : '&#xe0c1;',
			'icon-device-access-flash-automatic' : '&#xe0c0;',
			'icon-device-access-end-call' : '&#xe0bf;',
			'icon-device-access-dial-pad' : '&#xe0be;',
			'icon-device-access-data-usage' : '&#xe0bd;',
			'icon-device-access-camera' : '&#xe0bc;',
			'icon-device-access-call' : '&#xe0bb;',
			'icon-device-access-brightness-medium' : '&#xe0ba;',
			'icon-device-access-brightness-high' : '&#xe0b9;',
			'icon-device-access-brightness-auto' : '&#xe0b8;',
			'icon-device-access-bluetooth-searching' : '&#xe0b7;',
			'icon-device-access-bluetooth-connected' : '&#xe0b6;',
			'icon-device-access-bluetooth' : '&#xe0b5;',
			'icon-device-access-bightness-low' : '&#xe0b4;',
			'icon-device-access-battery' : '&#xe0b3;',
			'icon-device-access-alarms' : '&#xe0b2;',
			'icon-device-access-add-alarm' : '&#xe0b1;',
			'icon-device-access-accounts' : '&#xe0b0;',
			'icon-av-upload' : '&#xe0a1;',
			'icon-av-stop' : '&#xe0a0;',
			'icon-av-shuffle' : '&#xe09f;',
			'icon-av-rewind' : '&#xe09e;',
			'icon-av-return-from-full-screen' : '&#xe09d;',
			'icon-av-replay' : '&#xe09c;',
			'icon-av-repeat' : '&#xe09b;',
			'icon-av-previous' : '&#xe09a;',
			'icon-av-play-over-video' : '&#xe099;',
			'icon-av-play' : '&#xe098;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};